### ISSUE TITLE
(feat) Declarative CDK - define AWS CDK app declaratively

### ISSUE THREAD

**Issue by evgenyka** [aws-cloudformation/cfn-language-discussion#97]
## Description
[deCDK](https://github.com/cdklabs/decdk) tool is capable to read CloudFormation-like JSON/YAML templates which can contain both normal CloudFormation resources and also reference AWS CDK resources.
The proposal is to enable that functionality on CloudFormation server side in order to give customers ability to define AWS CDK applications declaratively.

## Checklist

- [x] Tracking issue created (label: `status/proposed`)
- [x] RFC pull request submitted 
- [ ] Reviewers assigned (label: `status/review`)
- [ ] Reviewers signed-off (label `approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Implementation started (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.
